config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :bookings
  resources :rooms
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :bookings
  # get 'home/index'
  get "home/about"
  

  root :to => 'home#index'  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end

  def about
    
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<footer class="text-center text-lg-start text-white"
        style="background-color: #45526e">
<div class="container-fluid">

<div class="container pt-5">

    <section class="">

    <div class="row">

        <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
        <h6 class="text-uppercase mb-4 font-weight-bold">
            Гостиница
        </h6>
        <p>

        </p>

        </div>
        
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
        <h6 class="text-uppercase mb-4 font-weight-bold">Контакты</h6>
        <p><i class="fas fa-home mr-3"></i>220114, г. Минск,  ул.Ф.Скорины, 4</p>
        <p><i class="fas fa-envelope mr-3"></i> hotel.mag@btg.by</p>
        <p><i class="fas fa-phone mr-3"></i>Тел./факс: +37517-374-01-16</p>
        </div>

    </div>
    </section>

    <hr class="my-3">

    <section class="p-3 pt-0">
    <div class="row d-flex align-items-center">
        <div class="col-md-7 col-lg-8 text-center text-md-start">
        <div class="p-3">
            © DedHook inc.
        </div>
        </div>
        <div class="col-md-5 col-lg-4 ml-lg-0 text-center text-md-end">
        <!-- Facebook -->
        <a  href="https://www.facebook.com/groups/146436772658640"
            class="btn btn-outline-light btn-floating m-1"
            class="text-white"
            role="button"
            ><i class="fab fa-facebook-f"></i
            ></a>
        <!-- Instagram -->
        <a href="https://www.instagram.com/gazhotel2017/"
            class="btn btn-outline-light btn-floating m-1"
            class="text-white"
            role="button"
            ><i class="fab fa-instagram"></i
            ></a>
        </div>
    </div>
    </section>
</div>
</div>
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Главная", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "О нас", home_about_path, class:"nav-link" %>
          <li class="nav-item">
            <%= link_to "Номера в гостиице", rooms_path, class:"nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav me-left mb-2 mb-lg-0">
          <% if user_signed_in?%>
            <li class="nav-item">
              <%= link_to "Изменить профиль", edit_user_registration_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Выход", destroy_user_session_path, class:"nav-link" %>
            </li>
          </li>
          <li class="nav-item">
            <%= link_to "Текущая бронь", bookings_path, class:"nav-link" %>
          </li>
        <%else%>
          <li class="nav-item">
            <%= link_to "Регистрация", new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Вход", new_user_session_path, class:"nav-link" %>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
<div class="container px-4 px-lg-5">
<br>

            <!-- Post title-->
            <h1 class="fw-bolder mb-1">Гостиница ОАО «Газпром трансгаз Беларусь»</h1>
          <!-- Preview image figure-->
          <figure class="mb-4"><img class="img-fluid rounded" src="https://i.ibb.co/CQLj9w0/glav-1.jpg" alt="..." /></figure>
          <!-- Post content-->
            <p class="fs-5 mb-4">Гостиница ОАО «Газпром трансгаз Беларусь» расположена недалеко от МКАД, в нескольких остановках от станции метро «Московская» и Национальной библиотеки. Из окон гостиницы открывается панорамный вид на живописный пейзаж. Близость лесопарковой зоны позволит на некоторое время почувствовать себя свободным от городского шума и суеты.

Для комфортного проживания гостям предлагаются одно-, двух- и трехкомнатные номера. В каждом из них имеется всё необходимое для размеренного отдыха: телефон, холодильник, телевизор. Также вы можете воспользоваться беспроводным доступом в интернет (Wi—Fi). В одном здании с гостиницей расположены кафе и магазин, которые удивят вас широким выбором продуктов и приятными ценами.</p>
 <figure class="mb-4"><img class="img-fluid rounded" src="https://i.ibb.co/w4GZKtn/g-1.jpg" alt="..." /></figure>
 <p class="fs-5 mb-4">Вас порадуют приветливость и внимание со стороны сотрудников, которые всегда готовы помочь. Профессионально подготовленный персонал обеспечит атмосферу гостеприимства и доброжелательности. Безопасность же гостей обеспечивают круглосуточная охрана и видеонаблюдение по периметру здания.</p>       
<figure class="mb-4"><img class="img-fluid rounded" src="https://i.ibb.co/d6B5Yr4/g-2.jpg" alt="..." /></figure>

<p class="fs-5 mb-4">Для удобства гостей предусмотрен индивидуальный подход к оплате услуг: наличный, безналичный расчет, оплата пластиковыми карточками.</p>
<figure class="mb-4"><img class="img-fluid rounded" src="https://i.ibb.co/cwMHBcR/g-3.jpg" alt="..." /></figure>
<p class="fs-5 mb-4">Гостям, приезжающим на личных автомобилях, мы предоставляем место на удобной бесплатной парковке с видеонаблюдением. </p>
<p class="fs-5 mb-4">Ждем Вас, мы всегда рады гостям!</p>


</div>

app/views/home/index.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<!------ Include the above in your HEAD tag ---------->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
<!------ Include the above in your HEAD tag ---------->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
<div class="container px-4 px-lg-5">
            <!-- Heading Row-->
            <div class="row gx-4 gx-lg-5 align-items-center my-5">
                <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="https://belarus-tr.gazprom.ru/d/textpage/0e/14/lighter.jpg" alt="..." /></div>
                <div class="col-lg-5">
                    <h1 class="font-weight-light">Гостиница ОАО "Газпром трансгаз Беларусь"</h1>
                    <p>Гостиница ОАО «Газпром трансгаз Беларусь» расположена недалеко от МКАД, в нескольких остановках от станции метро «Московская» и Национальной библиотеки. Из окон гостиницы открывается панорамный вид на живописный пейзаж. Близость лесопарковой зоны позволит на некоторое время почувствовать себя свободным от городского шума и суеты.</p>
                </div>
            </div>
            




<div class="container">


<div id="carouselExampleControls" class="carousel slide" data-ride="carousel" >
  <div class="carousel-inner">
    <div class="carousel-item active">

      <img class="d-block w-100" src="https://i.ibb.co/CQLj9w0/glav-1.jpg" alt="First slide">

    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://i.ibb.co/mqDzTWw/glav-2.jpg" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://i.ibb.co/HG47HDZ/glav-3.jpg" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
<br>
</div>